from app import app
from flask import render_template
from . import config
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
@app.route("/")
@app.route("/index")
def index():
    coordonees = {"lat": "48.8747265", "long": "2.3505517"}
    key = {"key" : config.Config.google_api}
    position ={"lat": coordonees.get("lat"), "long": coordonees.get("long")}
    return render_template("index.html", title="home", key=key, position=position)